### ISSUE TITLE
Rest api fdci eror ?

### ISSUE THREAD

**Issue by mrfzvx12** [farizdotid/DAFTAR-API-LOKAL-INDONESIA#105]
Infonya dong yang pinterest

**Comment by farizdotid** [comment]
Websitenya sepertinya yang error mas, untuk API barusan saya coba aman. Example : https://api.fdci.se/sosmed/rep.php?gambar=android

**Comment by mrfzvx12** [comment]
> Websitenya sepertinya yang error mas, untuk API barusan saya coba aman. Example : https://api.fdci.se/sosmed/rep.php?gambar=android

Iyaa bang work.. Mungkin di readme.md linknya langsung kesitu aja bang.. ntar dikira nggk work lagi..

**Comment by farizdotid** [comment]
@mrfzvx12 seinget saya dulu waktu nge review di link itu ada dokumentasi APInya mas. Saya bikin langsung aja kali ya linknya ke link tadi?

**Comment by mrfzvx12** [comment]
> @mrfzvx12 seinget saya dulu waktu nge review di link itu ada dokumentasi APInya mas. Saya bikin langsung aja kali ya linknya ke link tadi?

Iyaa bener gitu aja bang.. takutnya orang salah paham dikira nggk bisa.. keknya fdci yg work tinggal pinterest doang

**Comment by farizdotid** [comment]
@mrfzvx12 ok siap mas, thanks ya!
