### ISSUE TITLE
Pengkategorian API

### ISSUE THREAD

**Issue by dimasandhk** [farizdotid/DAFTAR-API-LOKAL-INDONESIA#125]
Halo, saya mau nambahin api data masjid dan mushalla di Indonesia kira2 itu termasuk kategori apa ya? Informasi umum, buku atau Pemerintahan? Soalnya sumber datanya dari kemen agama

**Comment by farizdotid** [comment]
@dimasandhk Masukin ke kategori Pemerintahan aja mas

**Comment by mfathurr** [comment]
> Halo, saya mau nambahin api data masjid dan mushalla di Indonesia kira2 itu termasuk kategori apa ya? Informasi umum, buku atau Pemerintahan? Soalnya sumber datanya dari kemen agama

Sudah ditambahkan ke daftar kak?
Untuk lihat website nya bisa dilihat dimana ya kak?
