### ISSUE TITLE
API lokasi offline?

### ISSUE THREAD

**Issue by DrDhemm** [farizdotid/DAFTAR-API-LOKAL-INDONESIA#130]
Halo mas, saya cek hari ini dari project saya, untuk API Lokasi Nama Daerah Seluruh Indonesia oleh Developer farizdotid di console katanya connection timed out. Apa sekarang sedang offline/maintenance?

![image](https://user-images.githubusercontent.com/55142840/121622075-8a0e5680-ca97-11eb-84a7-086ddf3550b0.png)

**Comment by farizdotid** [comment]
@DrDhemm Halo mas, sorry baru buka Github lagi hehe

Sepertinya iya mas waktu itu ada maintenance servernya
