### ISSUE TITLE
API COVID-19 Indonesia & Proxynya

### ISSUE THREAD

**Issue by vincenth19** [farizdotid/DAFTAR-API-LOKAL-INDONESIA#137]
Ini saya mau tambah API collection yang aku temukan sama reddit user [u/ThiccDemiglace](https://www.reddit.com/user/ThiccDemiglace/) dari [covid19.go.id](https://covid19.go.id).

Ini link dari documentation via [Postman Documenter](https://documenter.getpostman.com/view/16605343/Tzm6nwoS#d35f1c32-56d8-4af1-8d6e-ef3397653f99)

Kalau ada tambahan nanti updated di documentationnya.

Aku juga bikin backend untuk jadi proxy APIs tersebut. Ini [repoku](https://github.com/vincenth19/covidtracker-backend) dan ini [frontend](https://covidtracker.pages.dev/home) nya

**Comment by vincenth19** [comment]
Untuk link API proxyku ada disini: [Vercel](https://covidtracker-backend.vercel.app/api/) | [Heroku](https://covidtracker-vincenth19-be.herokuapp.com/api)

**Comment by fdciabdul** [comment]
Pull request aja mas

**Comment by sooluh** [comment]
Halo mas @vincenth19, API-nya udah ngga aktif ya kayanya?

**Comment by vincenth19** [comment]
> Halo mas @vincenth19, API-nya udah ngga aktif ya kayanya?

Iya sayang nya sudah tidak aktif dari pemerintah.

**Comment by sooluh** [comment]
barangkali bisa di close issue saja mas? karna sepertinya setelah dicari-cari, sistem informasi yg terkait covid sudah mulai di takedown semua.. data.covid19.go.id saja sudah tidak ada
