### ISSUE TITLE
Nitip KBBI API 

### ISSUE THREAD

**Issue by btrianurdin** [farizdotid/DAFTAR-API-LOKAL-INDONESIA#158]
Izin nitip KBBI API yang terbaru.
.
Link repository: https://github.com/btrianurdin/new-kbbi-api
Deskripsi: KBBI API yang dilengkapi dengan lema, kelas kata dan arti secara lengkap.
.
Terima kasih.

**Comment by farizdotid** [comment]
Langsung Pull Request aja mas
