### ISSUE TITLE
fork https://github.com/Zhirrr/islamic-rest-api-indonesian-v2 ?

### ISSUE THREAD

**Issue by olipiskandar** [farizdotid/DAFTAR-API-LOKAL-INDONESIA#164]
maaf teman-teman.. ada yang sudah fork dari [https://github.com/Zhirrr/islamic-rest-api-indonesian-v2](url) ?
kebetulan yg punya-nya ga bisa diakses lagi

**Comment by farizdotid** [comment]
@ZSofttt List API agan di repo ini saya hapus dulu ya gan. Nanti kalau udah aktif / ada link baru bisa langsung pull request aja ya. Thanks gan @ZSofttt

**Comment by mamasewibi** [comment]
ini sesui sunnah ga ya ? karna saya lihat Zhirrr/islamic-rest-api ada doa2 yg tidak sesuai sunnah ?

**Comment by sooluh** [comment]
mas @mamasewibi boleh ke https://github.com/fitrahive/dua-dhikr mas..

**Comment by mamasewibi** [comment]
masya allah , jazakallah khairan akhi

Pada Jum, 5 Jun 2026 pukul 09.44 Torch ***@***.***> menulis:
