### ISSUE TITLE
New Kategori khusus Agama/Islam

### ISSUE THREAD

**Issue by Ucok23** [farizdotid/DAFTAR-API-LOKAL-INDONESIA#201]
saya melihat di kategori buku, kebanyakan isinya Al-Quran api, apakah bisa dibuat khusus kategori al-quran atau kategori agama atau kategori islam agar tidak tercampur dengan buku umum?

**Comment by Ucok23** [comment]
jika boleh, saya mau contribute

**Comment by farizdotid** [comment]
@Ucok23 Boleh mas, Biasanya nanti saya review dulu.

**Comment by sooluh** [comment]
Halo mas @Ucok23, kategori Agama Islam sudah ditambahkan pada pull-request #315, terima kasih!
