### ISSUE TITLE
Izin nitip rest api bang

### ISSUE THREAD

**Issue by FERDIZ-afk** [farizdotid/DAFTAR-API-LOKAL-INDONESIA#204]
Bang Izin Nambah rest api kali aja ada yg butuh wkwkwk
FERDIZ-afk.my.id maklum bang fitur nya lagi di kembanging

**Comment by farizdotid** [comment]
@FERDIZ-afk Pull Request aja mas

**Comment by sooluh** [comment]
Maaf mas @FERDIZ-afk, API-nya ngga bisa di akses ya?

**Comment by FERDIZ-afk** [comment]
> Maaf mas @FERDIZ-afk, API-nya ngga bisa di akses ya?

E udah ganti domain kak ke oni-chan.my.id
