### ISSUE TITLE
Nitip RestAPI gan

### ISSUE THREAD

**Issue by rssdevoloper** [farizdotid/DAFTAR-API-LOKAL-INDONESIA#208]
https://freekeyapi.herokuapp.com

Maaf Gan ndak bisa pul request
Gk ngerti github

**Comment by farizdotid** [comment]
@rssdevoloper Silahkan bisa baca dokumentasinya disini mas : https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request

**Comment by sooluh** [comment]
Maaf mas @rssdevoloper, API-nya ngga bisa di akses ya?
