### ISSUE TITLE
API untuk mengetahui harga emas

### ISSUE THREAD

**Issue by saputraiqbal** [farizdotid/DAFTAR-API-LOKAL-INDONESIA#23]
Apakah untuk saat ini ada API yang bisa digunakan untuk mengetahui harga emas dan/atau logam2 lainnya di Indonesia? Soalnya datanya (terutama data harga emas dan perak) mau digunakan untuk menentukan nishab zakat
Terimakasih atas perhatiannya

**Comment by rizkyalayubi** [comment]
halo mas udah dapet belum? saya butuh juga ni

**Comment by k1m0ch1** [comment]
https://metals-api.com/
belum pernah coba tapi kelaitannya worth, sayangnya 50 api call perbulan.
keliatannya paling aman dibikin worker disimpen ke database dan dipanggil sehari sekali aja.

**Comment by saputraiqbal** [comment]
baik, terima kasih informasinya, kawan kawan :)
