### ISSUE TITLE
API Peta Sebaran COVID19 level kecamatan di Indonesia

### ISSUE THREAD

**Issue by thisisbintang** [farizdotid/DAFTAR-API-LOKAL-INDONESIA#24]
Permisi gan, saya bisa request API peta sebaran covid19 tingkat kecamatan? Terima kasih

**Comment by andriyfm** [comment]
Nunggu di approve sama authornya mas, saya udah pull request #25 moga2 manfaat

**Comment by bintang007** [comment]
Terima kasih mas, untuk tingkat kecamatan sendiri apakah anda juga memiliki API nya?

**Comment by farizdotid** [comment]
Sip udah saya merge mas @andriyfm . Terimakasih banyak mas!

**Comment by SonyPradana** [comment]
### Masalah CORS, sudah 2 hari terahir ini

> The Same Origin Policy disallows reading the remote resource at https://api.kawalcorona.com/indonesia/provinsi/. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).

solusi sementra pakai internal proxy

**Comment by sooluh** [comment]
Domain kawalcorona sudah tidak aktif, pedulilindungi juga sudah di suntik mati, COVID sudah menjadi endemi, dan itu sudah 3-4 tahun yang lalu, saya izin close issue 🙂
