### ISSUE TITLE
Api

### ISSUE THREAD

**Issue by isKazumi** [farizdotid/DAFTAR-API-LOKAL-INDONESIA#242]
## Informasi API

**Nama API**:
**Developer**:
**API Endpoint/Dokumentasi**:
**Status**:
**Deskripsi**:
**Auth**:

### Penjelasan API

jelaskan secara singkat tentang bagaimana API anda bekerja dan apa saja yang harus dilakukan oleh peserta.

**Comment by flamrdevs** [comment]
Kalau ada yang kontribusi.......

[Indonesia API](https://github.com/indonesia-api/indonesia-api)
