### ISSUE TITLE
API Gardu PLN

### ISSUE THREAD

**Issue by wiscaksono** [farizdotid/DAFTAR-API-LOKAL-INDONESIA#246]
***Jelaskan masalahnya**
URL API tidak bisa diakses, kemungkinan endpointnya berubah

**Luaran/Output yang diharapkan**
Data gardu PLN

**Screenshot**
![image](https://user-images.githubusercontent.com/63142229/191428847-c30f859c-d723-46ac-b8cf-5833fba36031.png)

**Comment by sooluh** [comment]
Halo mas @wiscaksono, maaf, kayanya emang udah ditakedown dari PLN-nya, karena API itu juga udah ngga ada di daftar :grin:
