### ISSUE TITLE
Alkitab API

### ISSUE THREAD

**Issue by raselldev** [farizdotid/DAFTAR-API-LOKAL-INDONESIA#265]
## Informasi API

**Nama API**: Alkitab API
**Developer**: RasellDev
**API Endpoint/Dokumentasi**: https://github.com/raselldev/alkitab-api 
**Status**: Done (Docker Images)
**Deskripsi**: Alkitab API yang di tarik dari sabda.org
**Auth**: No

### Penjelasan API

API ini adalah berisi ayat ayat alkitab yang langsung ditarik dari website sabda.org dan juga untuk saat ini saya hanya publish docker image saja. Next saya akan publish API ini untuk kepentingan semuanya.

**Comment by farizdotid** [comment]
@raselldev Pull Request aja gan
