### ISSUE TITLE
Data BMKG has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource

### ISSUE THREAD

**Issue by ujangaripin24** [farizdotid/DAFTAR-API-LOKAL-INDONESIA#276]
izin Admin untuk menyampaikan masalah
has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource
saya menggunakan link dari BMKG ['https://data.bmkg.go.id/DataMKG/TEWS/gempadirasakan.json'] tersebut, tapi pas saya mau tampilkan di console.log() muncul error
'Access to XMLHttpRequest at 'https://data.bmkg.go.id/DataMKG/TEWS/gempadirasakan.json' from origin 'http://localhost:8080' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.'
itu kenapa yah? mohon jawab Admin

**Comment by vzrenggamani** [comment]
Sudah mencoba pakai format XML mas? 

error `No 'Access-Control-Allow-Origin'` terjadi jika sisi server penyedia data tidak memperbolehkan adanya akses terhadap konten di dalamnya jika hostname dari `get client` tidak dikenal.

**Comment by ujangaripin24** [comment]
> 

kalo pake xml aku belum coba mas, oalahh jadi butuh izin gitu yah ke bmkg nya berarti perlu API key yah mas?

**Comment by ujangaripin24** [comment]
sama ternyata mas, aku coba masih block by CORS

**Comment by vzrenggamani** [comment]
Mas @ujangaripin24 menconsume API-nya menggunakan apa mas? apakah dari sisi server atau web apps?
Jika melalui webapps, lebih baik mungkin jika diconsume melalui sisi server sehingga tidak terjadi permintaan melalui sebuah hostname, jika menggunakan NodeJS potongan kode berikut mungkin bisa membantu mas

```js
// index.js
var axios = require('axios');

var config = {
  method: 'get',
maxBodyLength: Infinity,
  url: 'https://data.bmkg.go.id/DataMKG/TEWS/gempadirasakan.json',
  headers: { }
};

axios(config)
.then(function (response) {
  console.log(JSON.stringify(response.data));
})
.catch(function (error) {
  console.log(error);
});
```

atau bisa mencoba mengcalling dari pureJS 

```js
var requestOptions = {
  method: 'GET',
  redirect: 'follow'
};

fetch("https://data.bmkg.go.id/DataMKG/TEWS/gempadirasakan.json", requestOptions)
  .then(response => response.text())
  .then(result => console.log(result))
  .catch(error => console.log('error', error));
```

Error No-Cross origin seringkali terjadi jika permintaan data dilakukan melalui sisi webapps

**Comment by ujangaripin24** [comment]
aku juga pake axios dan makasih mas ini sekarang berhasil

**Comment by vzrenggamani** [comment]
Wah great to hear that mas @ujangaripin24, jika boleh mungkin bisa dielaborasi solvingnya seperti apa atau potongan kode sebelum dan sesudahnya seperti apa. Biar menjadi wawasan bagi teman" yang ada di sini
