### ISSUE TITLE
Tambah API

### ISSUE THREAD

**Issue by TheAlexSandro** [farizdotid/DAFTAR-API-LOKAL-INDONESIA#278]
## Informasi API

**Nama API**: NekoBot
**Developer**: --
**API Endpoint/Dokumentasi**: https;//docs.nekobot.xyz
**Status**: Aktif
**Deskripsi**: API untuk membuat berbagai macam gambar
**Auth**: Tidak ada

### Penjelasan API

API ini dapat membuat berbagai macam gambar, seperti captcha, animeface, dll. Caranya adalah pergi ke docsnya dan pilih salah satu API yang mau dipakai.

Maap bang, gk bisa pull request :)

**Comment by vzrenggamani** [comment]
Boleh dilakukan forking terlebih dahulu @TheAlexSandro atau bisa diberitahu link repository yang sudah melakukan penambahan, akan saya coba ajukan PR dari sisi repository
