### ISSUE TITLE
Error API Daerah Indonesia | RTO API

### ISSUE THREAD

**Issue by rahulken96** [farizdotid/DAFTAR-API-LOKAL-INDONESIA#288]
Hallo.. mau report nih bang.. status untuk API Daerah Indonesia lagi RTO ya?? Apakah ada alternatif API untuk Daerah Indonesia?

![image](https://user-images.githubusercontent.com/77185853/236403994-1ad57be3-3238-480e-8245-63436e98f202.png)

![image](https://user-images.githubusercontent.com/77185853/236403775-4c6273a6-f39a-4b18-b5b1-91c838052eae.png)

**Comment by farizdotid** [comment]
@rahulken96 Sudah normal kembali, Mas. Kayanya tadi sempert down

**Comment by rahulken96** [comment]
Oh oke.. udah jalan juga mas.. makasih juga untuk API nya 👍👍
