### ISSUE TITLE
Tambah API (Forest API)

### ISSUE THREAD

**Issue by rioagungpurnomo** [farizdotid/DAFTAR-API-LOKAL-INDONESIA#292]
## Informasi API

**Nama API**: [Forest API](https://github.com/rioagungpurnomo/forestapi) 
**Developer**: [Rio Agung Purnomo](https://github.com/rioagungpurnomo) 
**API Endpoint/Dokumentasi**: https://forestapi.my.id
**Status**: Aktif
**Deskripsi**: Kumpulan API gratis tanpa batas yang dapat digunakan kapan saja dan di mana saja.
**Auth**: Tidak

### Penjelasan API
Kumpulan API gratis tanpa apikey dan limit, daftar API
- [Github API](https://forestapi.my.id/api/github)
- [Facebook API](https://forestapi.my.id/api/facebook) 
- [WhatsApp API](https://forestapi.my.id/api/whatsapp) 
- [Instagram API](https://forestapi.my.id/api/instagram) 
- [Telegram API](https://forestapi.my.id/api/telegram) 
- [YouTube API](https://forestapi.my.id/api/youtube) 
- [TikTok API](https://forestapi.my.id/api/tiktok) 
- [Snapchat API](https://forestapi.my.id/api/snapchat)

**Comment by farizdotid** [comment]
@rioagungpurnomo Pull Request aja mas

**Comment by rioagungpurnomo** [comment]
Oke baik nanti tolong di acc ya mas

**Comment by rioagungpurnomo** [comment]
Tolong masukin mas

|Github API|[Rio Agung Purnomo](https://github.com/rioagungpurnomo)| [Link](https://forestapi.up.railway.app/api/github) |`Aktif`|Ambil informasi User, Daftar Pengikut, Daftar Mengikuti, Daftar Bintang, Repositori, Daftar Bintang Repositori, Daftar Garpu Repositori|Tidak|
|YouTube API|[Rio Agung Purnomo](https://github.com/rioagungpurnomo)| [Link](https://forestapi.up.railway.app/api/youtube) |`Aktif`|Ambil informasi Channel, Video|Tidak|
|Facebook API|[Rio Agung Purnomo](https://github.com/rioagungpurnomo)| [Link](https://forestapi.up.railway.app/api/facebook) |`Aktif`|Ambil informasi User, Halaman, Grup, Video|Tidak|
|Instagram API|[Rio Agung Purnomo](https://github.com/rioagungpurnomo)| [Link](https://forestapi.up.railway.app/api/instagram) |`Aktif`|Ambil informasi User, Photo, Video|Tidak|
|Telegram API|[Rio Agung Purnomo](https://github.com/rioagungpurnomo)| [Link](https://forestapi.up.railway.app/api/telegram) |`Aktif`|Ambil informasi User, Grup, Channel|Tidak|
|TikTok API|[Rio Agung Purnomo](https://github.com/rioagungpurnomo)| [Link](https://forestapi.up.railway.app/api/tiktok) |`Aktif`|Ambil informasi User, Video|Tidak|
|WhatsApp API|[Rio Agung Purnomo](https://github.com/rioagungpurnomo)| [Link](https://forestapi.up.railway.app/api/whatsapp) |`Aktif`|Ambil informasi Grup|Tidak|

**Comment by AsianTradeFX** [comment]
Ok
