### ISSUE TITLE
Tambah API (Bhinneka)

### ISSUE THREAD

**Issue by fitrailham** [farizdotid/DAFTAR-API-LOKAL-INDONESIA#294]
## Informasi API

**Nama API**: Bhinneka API
**Developer**: Fitra Ilham
**API Endpoint/Dokumentasi**: http://mock-api.bhinneka.com/
**Status**: Aktif
**Deskripsi**: Kumpulan API Bhinneka patnership, B2G, B2B, Product.
**Auth**: Tidak

### Penjelasan API

API ini adalah berisi layanan yang dilakukan oleh bhinneka seperti notifikasi service, product catalog, dan user service API

**Comment by farizdotid** [comment]
@fitrailham Di pull request aja mas

**Comment by sooluh** [comment]
Halo mas @fitrahilham, API endpoint-nya sudah tidak bisa diakses ya?
