### ISSUE TITLE
Tambahkan API PuloDev

### ISSUE THREAD

**Issue by nauwimanuel** [farizdotid/DAFTAR-API-LOKAL-INDONESIA#297]
Informasi API
Nama API: [API PuloDev](https://pulo.dev/api/)
Status: Aktif
Auth: Tidak ada
Deskripsi: API Kumpulan konten developer Indonesia.
Developer: [Juan Akbar](https://github.com/jeins), [Yohan Totting](http://tyohan.me/), [Chaidir Yahya](http://github.com/chaidiryahya), [Fauzi Sanjaya](https://github.com/fauxxi), dan [Hilman Ramadhan](https://hilman.space/)

Dokumentasi: https://pulo.dev/api/
API Endpoint/[Semua Konten]
https://api.pulo.dev/v1/contents

API Endpoint/[Filter halaman]
https://api.pulo.dev/v1/contents?page=1

API Endpoint/[Filter media: bisa "web, tulisan, podcast atau video"]
https://api.pulo.dev/v1/contents?media=web

API Endpoint/[Filter Text]
https://api.pulo.dev/v1/contents?query=laravel

**Comment by farizdotid** [comment]
@nauwimanuel Di pull request aja mas

**Comment by sooluh** [comment]
sepertinya project PuloDev sudah tidak dilanjutkan sama mas Hilman ya, saya izin close issue :grin:
