### ISSUE TITLE
Dead Link

### ISSUE THREAD

**Issue by jarooda** [farizdotid/DAFTAR-API-LOKAL-INDONESIA#314]
beberapa link API sudah tidak bisa diakses, dan sepertinya ini karena api tersebut dibuat oleh pribadi dan tidak di maintain

example:

Viko API |	VikoDK |	[Link](https://viko-api.herokuapp.com/) | Aktif | Rest API gratis hasil scrape & tembak | apikey
-- | -- | -- | -- | -- | --

Hadi API | m hadi firmansya | [Link](https://hadi-api.cf/api) | Aktif | Rest api GRATIS | Tidak
-- | -- | -- | -- | -- | --

LK API | Loli killers | [Lk](https://api.loli.loveslife.biz/) | Aktif | Free rest api | Apikey
-- | -- | -- | -- | -- | --

---

**Comment by sooluh** [comment]
Hai @jarooda, API-API tersebut sudah tidak ada di daftar, harap tutup Issue ini, terima kasih!

**Comment by jarooda** [comment]
nice
