### ISSUE TITLE
Update file to PR

### ISSUE THREAD

**Issue by Z4nR** [farizdotid/DAFTAR-API-LOKAL-INDONESIA#349]
#347 udah saya update berkas di folder datanya mas. apakah udh memenuhi syarat? makasih

**Comment by sooluh** [comment]
maaf mas @Z4nR, untuk diskusi terkait pull-request, cukup di pull-request saja ya, jangan open issue :pray:

**Comment by Z4nR** [comment]
oiya mas maap maap
