### ISSUE TITLE
Tambah API multi

### ISSUE THREAD

**Issue by rssdevoloper** [farizdotid/DAFTAR-API-LOKAL-INDONESIA#359]
## Informasi API

**Nama API**: Rassa API
**Pengembang**: Rangga
**Tautan Profil Pengembang**: https://github.com/rssdevoloper
**Tautan Dokumentasi**: ranggapanel.me/docs
**Status**: aktif
**Deskripsi**: Api Multi Guna
**Autentikasi**: Apikey

### Penjelasan API

Jelaskan secara singkat tentang bagaimana API anda bekerja dan apa saja yang harus dilakukan oleh peserta.

--- Restapi Dengan berbagai fitue seperti downloader, create, tools, ai, dll

Dengan mengajukan pull request atau issue pada repositori ini, saya menyatakan bahwa tautan RESTful API yang saya sertakan tidak akan mengandung konten NSFW (Not Safe for Work).

**Comment by sooluh** [comment]
Maaf mas @rssdevoloper, saya baru notice issue ini, pas saya buka connection timeout mas, mungkin bisa di fix dulu nanti InsyaAllah saya bantu pull-request kan.

**Comment by rssdevoloper** [comment]
@sooluh udah mas gk jadi
