### ISSUE TITLE
Link API tiket.com rusak

### ISSUE THREAD

**Issue by danilhendras** [farizdotid/DAFTAR-API-LOKAL-INDONESIA#41]
Link API tiket.com
![image](https://user-images.githubusercontent.com/45989466/90013477-88390280-dccf-11ea-9818-de552752197a.png)

Berikut ketika link di atas diklik:
![image](https://user-images.githubusercontent.com/45989466/90013530-a141b380-dccf-11ea-9510-7b44d76156ea.png)

**Comment by farizdotid** [comment]
Sekarang sudah bisa mas @danilhendras

**Comment by danilhendras** [comment]
Terimakasih, issue closed

**Comment by farizdotid** [comment]
Terimakasih kembali mas!
