### ISSUE TITLE
Link API Doku rusak

### ISSUE THREAD

**Issue by danilhendras** [farizdotid/DAFTAR-API-LOKAL-INDONESIA#42]
Berikut link yang dimaksud:
![image](https://user-images.githubusercontent.com/45989466/90013655-e2d25e80-dccf-11ea-97bf-ba6cb13ac7ad.png)

Berikut ketika link dikunjungi:
![image](https://user-images.githubusercontent.com/45989466/90013691-f7165b80-dccf-11ea-9a0b-ae3365e72302.png)

**Comment by farizdotid** [comment]
Sekarang sudah bisa mas @danilhendras
