### ISSUE TITLE
Semua link API karya Wahid rusak

### ISSUE THREAD

**Issue by danilhendras** [farizdotid/DAFTAR-API-LOKAL-INDONESIA#43]
Terdapat 2 API karya Wahid yg tercantum di file README, yaitu cek resi dan jadwal sholat
![image](https://user-images.githubusercontent.com/45989466/90013921-64c28780-dcd0-11ea-8f8f-a9b8da9332fc.png)
![image](https://user-images.githubusercontent.com/45989466/90013944-6db35900-dcd0-11ea-9c5c-d9b03457feb7.png)

Kedua link di atas ketika dikunjungi akan tampil seperti berikut:
![image](https://user-images.githubusercontent.com/45989466/90013974-7c9a0b80-dcd0-11ea-9106-508480b1babd.png)

**Comment by farizdotid** [comment]
Sudah saya update mas, Terimakasih mas @danilhendras !
