### ISSUE TITLE
Beberapa API karya iBachor rusak

### ISSUE THREAD

**Issue by Zzzul** [farizdotid/DAFTAR-API-LOKAL-INDONESIA#45]
### Daftar API yang rusak
![haji](https://user-images.githubusercontent.com/62506582/90720664-3c92e400-e2e1-11ea-86a8-ed626ab2aea0.png)

Link
https://sites.google.com/macros/exec?service=AKfycbyfd-1n79k0TDYFbcI4XI28zDdiK8aeCcWzLtNH97jfr3xoPpg&nomor=100137466

Ketika link dikunjungi
![haji](https://user-images.githubusercontent.com/62506582/90720741-5e8c6680-e2e1-11ea-9c44-ab9ccbb59e8b.png)

<br>

<hr>

![produk halal](https://user-images.githubusercontent.com/62506582/90720671-3f8dd480-e2e1-11ea-83fd-4edc7a0bb752.png)

Link
https://sites.google.com/macros/exec?service=AKfycbx_-gZbLP7Z2gGxehXhWMWDAAQsTp3e3bmpTBiaLuzSDQSbIFWD&menu=nama_produk&query=abc

Ketika link dikunjungi
![produk halal](https://user-images.githubusercontent.com/62506582/90720756-64824780-e2e1-11ea-9a4c-f5cb28575242.png)

<br>

<hr>

![lirik lagu](https://user-images.githubusercontent.com/62506582/90720674-41f02e80-e2e1-11ea-9998-f4a3428b3204.png)
Link API untuk lirik lagu sudah tidak tersedia di repo https://github.com/bachors/apiapi

**Comment by farizdotid** [comment]
Removed mas @Zzzul . Terimakasih!
