### ISSUE TITLE
Informasi penambahanan api

### ISSUE THREAD

**Issue by ossas4648** [farizdotid/DAFTAR-API-LOKAL-INDONESIA#46]
Ini mas barangkali bisa di masukkan API tentang Film luar / dalam negeri

https://www.themoviedb.org/documentation/api

**Comment by farizdotid** [comment]
oh iya ya bisa, tinggal di setup untuk data movie Indonesia aja. Thanks mas @ossas4648 !

**Comment by ossas4648** [comment]
Siapp

**Comment by farizdotid** [comment]
done mas @ossas4648 !
