### ISSUE TITLE
Tanya API untuk KBBI terbaru

### ISSUE THREAD

**Issue by aryomuzakki** [farizdotid/DAFTAR-API-LOKAL-INDONESIA#61]
Apakah ada API untuk KBBI yang terbaru?
dan adakah API untuk mengambil kata tertentu dari daftar kata di KBBI?

saya dapat API dari [Kateglo](https://kateglo.com/api.php), tapi di [Github Kateglo](https://github.com/ivanlanin/kateglo) saya lihat terakhir aktif 2014, mungkin ada yang tau sumber lain?

**Comment by Zhirrr** [comment]
https://github.com/zhirrr/KBBI-api

Ini Mank Bisa Coba Aja, Kalo Mau Punya Sendiri Tinggal Fork Trus Deploy Ke Vercel >_<

**Comment by sooluh** [comment]
Hai mas @aryomuzakki, API KBBI baru sudah tersedia di kategori [Pendidikan](https://github.com/farizdotid/DAFTAR-API-LOKAL-INDONESIA?tab=readme-ov-file#pendidikan) yaa :raised_hands:
