### ISSUE TITLE
docs.Tiket.com gak bisa diakses

### ISSUE THREAD

**Issue by Paper17mind** [farizdotid/DAFTAR-API-LOKAL-INDONESIA#64]
untuk dokumentasi api tiket.com gak bisa di akses ya ? atau url nya diganti ?

**Comment by farizdotid** [comment]
oh iya mas barusan saya cek juga dokumentasinya ga ada. Saya hapus aja ya. Thanks mas @Paper17mind

**Comment by farizdotid** [comment]
Barusan saya cek aman mas linknya bisa diakses

**Comment by Paper17mind** [comment]
OK, makasih banyak mas info nya

**Comment by BerTren-Nation** [comment]
@farizdotid Mau Bilang api [parking_ocr Engak Ada](https://github.com/elybin/parking_ocr)

**Comment by farizdotid** [comment]
@BerTren-Nation Di list daftar api juga ga ada mas, atau namanya apa ya?

**Comment by sooluh** [comment]
Halo @Paper17mind, untuk API Tiket.com sepertinya sudah tidak ada di daftar, saya izin close issue ya :grin:
