### ISSUE TITLE
apakah ada API light novel indonesia?

### ISSUE THREAD

**Issue by nahansans** [farizdotid/DAFTAR-API-LOKAL-INDONESIA#68]

**Comment by farizdotid** [comment]
Barusan saya searching belum dapet mas. Mungkin temen-temen yang lain ada yang punya referensinya?

**Comment by nahansans** [comment]
saya dapet API novel cuman pake bahasa inggris
https://github.com/Kevin-Umali/novel-api

**Comment by putrilest** [comment]
Minta bantuannya temen temen ada yang punya rest api tentang nnovel?

**Comment by mazushishounen** [comment]
nitip
