### ISSUE TITLE
CORS

### ISSUE THREAD

**Issue by rayfajars** [farizdotid/DAFTAR-API-LOKAL-INDONESIA#78]
![cors](https://user-images.githubusercontent.com/58242304/103442352-fc2c7500-4c87-11eb-8448-8f7fde62bd98.JPG)
![cors2](https://user-images.githubusercontent.com/58242304/103442354-fdf63880-4c87-11eb-924c-d8060d1ea2d4.JPG)

kalo cors ini kenapa ya gan ?

ane coba get pake ajax, malah ke blok

**Comment by farizdotid** [comment]
@rayfajars Coba kontak developer APInya gan

**Comment by sooluh** [comment]
@rayfajars, maaf API-nya udah ngga ada di daftar dan mungkin developer-nya udah ngga maintain lagi, saya izin close issue ya :grin:
