### ISSUE TITLE
Masala cors api dari farizdotid 

### ISSUE THREAD

**Issue by El-Mahbub** [farizdotid/DAFTAR-API-LOKAL-INDONESIA#9]
Saya coba meload data api di farizdotid.com dari localhost, tapi error : 'Access-Control-Allow-Origin' (Masalah cors issue) .
Apakah harus login dan signup dulu atau gimana ? :D , karena untuk bisa mengakses api tersebut harus ada izin dari web asal (whitelist).
Tolong bantuannya :-)

**Comment by farizdotid** [comment]
waktu nge hit API yang mana gan ? @El-Mahbub biar saya coba fix.

**Comment by aulrahman** [comment]
> 
> 
> waktu nge hit API yang mana gan ? @El-Mahbub biar saya coba fix.

Salah satunya yang lokasi provinsi gan

**Comment by farizdotid** [comment]
Di saya ga ngalamin hal seperti ini gan. Mungkin ada detail atau screenshotnya? @aulrahman

**Comment by aulrahman** [comment]
> 
> 
> Di saya ga ngalamin hal seperti ini gan. Mungkin ada detail atau screenshotnya? @aulrahman

![cors](https://user-images.githubusercontent.com/10452818/46881285-49d52100-ce75-11e8-9c65-45b3aea53ef0.png)

Seperti itu gan.

**Comment by farizdotid** [comment]
Woala iya ternyata ada kodingan yang ngatur gituan. Udah saya hapus gan silahkan dicoba lagi @aulrahman

**Comment by farizdotid** [comment]
Sudah aman kah gan @aulrahman ?

**Comment by nazordz** [comment]
masih gk bisa gan....

diblock klo pake localhost

**Comment by farizdotid** [comment]
kalau sekarang giman mas @nazordz ? maaf mas saya agak slow respon
